name: Deploy SSRS Report

on:
  push:
    branches:
      - main

jobs:
  deploy_report:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ReportingServicesTools module
        shell: pwsh
        run: Install-Module -Name ReportingServicesTools -Force -Scope CurrentUser

      - name: Install ReportingServicesTools module
        shell: pwsh
        run: |
         ./DeployReport.ps1
