name: Check Local MSSQL Database on Push to Main

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and run MSSQL Docker container
        run: |
          sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong@Password122' -p 1433:1433 -d --name mssql-server -v $(pwd):/scripts mcr.microsoft.com/mssql/server:2019-latest

      - name: Wait for MSSQL to start
        run: |
          echo "Waiting for MSSQL server to start..."
          sleep 30 # Wait for 30 seconds

      - name: Run database query from file
        run: |
          sqlcmd -S ${{URL}} -U sa -P P@$$word20244 -i UpdateScripts/Scripts.sql || echo "sqlcmd failed with exit code $?"
