# This is a YAML file named "Check MSSQL Database"
name: Check MSSQL Database

# The workflow is triggered on each push to the main branch
on:
  push:
    branches:
      - main

# The workflow defines a single job named "check_database"
jobs:
  check_database:
    # The job runs on a machine with the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Download and run MSSQL Docker container
      - name: Download and run MSSQL Docker container
        run: |
          sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong@Password122' -p 1433:1433 -d --name mssql-server -v $(pwd):/scripts mcr.microsoft.com/mssql/server:2019-latest

      # Step 3: Wait for MSSQL to start (default wait time is 10 seconds)
      - name: Wait for MSSQL to start
        run: |
          echo "Waiting for MSSQL server to start..."
          sleep 10 # Wait for 10 seconds

      # Step 4: Run database query from file using sqlcmd
      - name: Run database query from file
        run: |
          sqlcmd -S 6.tcp.eu.ngrok.io,19373 -U sa -P P@$$word20244 -i UpdateScripts/Scripts.sql || echo "sqlcmd failed with exit code $?"
