name: Check Local MSSQL Database on Push to Main

on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and run MSSQL Docker container
        run: |
          sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong@Password122' -p 1433:1433 -d --name mssql-server -v $(pwd):/scripts mcr.microsoft.com/mssql/server:2019-latest

      - name: Wait for MSSQL to start
        run: |
          sleep 10 

      - name: Create and Populate Database
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USERNAME }} -P ${{ secrets.SQL_PASSWORD }} -i UpdateScripts/Scripts.sql || echo "sqlcmd failed with exit code $?"
