on:
  push:
    branches:
      - main

jobs:
  check_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and run MSSQL Docker container
        run: |
          sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong@Password122' -p 1433:1433 -d --name mssql-server -v $(pwd):/scripts mcr.microsoft.com/mssql/server:2019-latest

      - name: Wait for MSSQL to start
        run: |
          sleep 30 

      - name: Show Database in Local Server 
        run: |
          sudo docker exec -i mssql-server /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Password122 -Q 'SELECT name FROM sys.databases;'
